## Static Resources Configuration
#spring.web.resources.static-locations=classpath:/static/
#spring.mvc.static-path-pattern=/**
#spring.web.resources.cache.period=0
#spring.web.resources.chain.cache=false
#spring.web.resources.chain.enabled=true
#spring.web.resources.chain.strategy.content.enabled=true
#spring.web.resources.chain.strategy.content.paths=/**
#spring.web.resources.chain.strategy.fixed.enabled=true
#spring.web.resources.chain.strategy.fixed.paths=/js/**,/css/**,/images/**
#spring.web.resources.chain.strategy.fixed.version=v1
#
## PostgreSQL DB Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=monkeydonkey
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.default_schema=swapkartdb
#
#
## Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#
#
## Flyway Configuration
#spring.flyway.enabled=true
#spring.flyway.baseline-on-migrate=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.schemas=swapkartdb
#
## HikariCP Configuration (default in Spring Boot)
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.maximum-pool-size=2
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.pool-name=SpringBootHikariCP
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000
#
#spring.thymeleaf.check-template-location=false
#
## JWT Configuration
#jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#jwt.expiration=86400000
#
## Security configuration is now handled by DefaultAdminConfig
#
## CORS Allowed Origins (comma-separated)
#cors.allowed-origins=http://localhost:8081
#,http://localhost:4200,http://localhost:8909
#
## Logging
#logging.level.org.springframework.security=DEBUG
#logging.level.com.swapkart=DEBUG
